AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Trigger for gfe-db update pipeline
Globals:
  Function:
    Timeout: 60

Parameters:
  TriggerFunctionName:
    Type: String
  GitHubPersonalAccessToken:
    Type: String
  GitHubRepositoryOwner: 
    Type: String
  GitHubRepositoryName:
    Type: String
  DataBucketName:
    Type: String

Resources:
  TriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref TriggerFunctionName
      CodeUri: src
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment:
        Variables:
          GITHUB_PERSONAL_ACCESS_TOKEN: !Ref GitHubPersonalAccessToken
          GITHUB_REPOSITORY_OWNER: !Ref GitHubRepositoryOwner
          GITHUB_REPOSITORY_NAME: !Ref GitHubRepositoryName
          GFE_BUCKET: !Ref DataBucketName
      Events:
        Trigger:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
