AWSTemplateFormatVersion: '2010-09-09'
Description: Graph database representing IPD-IMGT/HLA sequence data as GFE
Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Stage of production
  AppName:
    Type: String
    Default: gfe-db
    Description: Application name
  Neo4jDatabaseImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  BuildImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
    Description: ECS Optimized Amazon Linux 2 AMI
  DataBucketName:
    Type: String
    Default: "bucket name"
    Description: Name of bucket for data, templates, and logs
Resources:
  DatabaseStack:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: !Join # Can be replaced with export
          - "/"
          - - !Sub "https://s3.${AWS::Region}.amazonaws.com"
            - !Ref DataBucketName
            - templates
            - database-stack.yml
        Parameters:
          Stage: !Ref Stage
          AppName: !Ref AppName
          EC2KeyPairName:
            Fn::ImportValue:
              !Sub "${Stage}-${AppName}-setup-EC2KeyPairName"
          Neo4jDatabaseImageId: !Ref Neo4jDatabaseImageId
          DataBucketArn: 
            Fn::ImportValue:
              !Sub "${Stage}-${AppName}-setup-DataBucketArn"
        Tags:
          - Key: AppName
            Value: !Ref AppName
          - Key: Stage
            Value: !Ref Stage
  UpdatePipelineStack:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: !Join
          - "/"
          - - !Sub "https://s3.${AWS::Region}.amazonaws.com"
            - !Ref DataBucketName
            - templates
            - update-pipeline-stack.yml
        Parameters:
          Stage: !Ref Stage
          AppName: !Ref AppName
          VPC: !GetAtt DatabaseStack.Outputs.VPC
          PublicSubnet: !GetAtt DatabaseStack.Outputs.PublicSubnet
          BuildImageId: !Ref BuildImageId
          DataBucketName: 
            Fn::ImportValue:
              !Sub "${Stage}-${AppName}-setup-DataBucketName"
          DataBucketArn: 
            Fn::ImportValue:
              !Sub "${Stage}-${AppName}-setup-DataBucketArn"
          Neo4jDatabaseEndpoint: !GetAtt DatabaseStack.Outputs.Neo4jDatabaseEndpoint
        Tags:
          - Key: AppName
            Value: !Ref AppName
          - Key: Stage
            Value: !Ref Stage
Outputs:
  UpdatePipelineExecutionInput:
    Description: Example input for the database update pipeline
    Value: |-
      {
          "params": {
              "environment": {
                  "RELEASES": "3450",
                  "ALIGN": "False",
                  "KIR": "False",
                  "MEM_PROFILE": "False",
                  "LIMIT": ""
              }
          }
      }