AWSTemplateFormatVersion: "2010-09-09"
Description: "gfe-db build service using AWS Batch"
# Parameters:
Resources:
  gfeDBPipelineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2008-10-17"
        Statement:
          - Sid: ""
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      Policies:
        - PolicyName: gfeDBPipelineLogsPolicy
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: "*"
        - PolicyName: gfeDBPipelineBatchExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - batch:SubmitJob
                  - batch:DescribeJobs
                  - batch:TerminateJob
                Resource: "*"
              - Effect: Allow
                Action: 
                  - events:PutTargets
                  - events:PutRule
                  - events:DescribeRule
                Resource: 
                  - !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForBatchJobsRule
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: gfe-db-pipeline
      RoleArn: !GetAtt gfeDBPipelineExecutionRole.Arn #
      DefinitionString: |-
        {
            "StartAt": "BUILD_GFE-DB",
            "States": {
                "BUILD_GFE-DB": {
                    "Type": "Task",
                    "Resource": "arn:aws:states:::batch:submitJob.sync",
                    "Parameters": {
                        "JobDefinition": "gfedbBatchJobDefinition",
                        "JobName": "build-gfe-db",
                        "JobQueue": "gfedbBatchProcessingJobQueue",
                        "ContainerOverrides": {
                            "Environment": [
                                {
                                    "Name": "RELEASES",
                                    "Value.$": "$.params.environment.RELEASES"
                                },
                                {
                                    "Name": "ALIGN",
                                    "Value.$": "$.params.environment.ALIGN"
                                },
                                {
                                    "Name": "KIR",
                                    "Value.$": "$.params.environment.KIR"
                                },
                                {
                                    "Name": "MEM_PROFILE",
                                    "Value.$": "$.params.environment.MEM_PROFILE"
                                }
                            ]
                        }
                    },
                    "End": true
                }
            }
        }
      LoggingConfiguration: 
        Destinations:
          - CloudWatchLogsLogGroup: 
              LogGroupArn: !GetAtt gfeDBPipelineLogGroup.Arn
        IncludeExecutionData: true
        Level: ALL
  gfeDBPipelineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: gfe-db-pipeline-execution-logs
Outputs:
  WorkflowArn:
    Description: Workflow statemachine ARN
    Value: !Ref StateMachine
  WorkflowName:
    Description: Workflow statemachine Name
    Value: !GetAtt StateMachine.Name
  WorkflowInput:
    Description: Example input for workflow statemachine
    Value: |-
      {
          "params": {
              "environment": {
                  "RELEASES": "3410,3420",
                  "ALIGN": "True",
                  "KIR": "False",
                  "MEM_PROFILE": "False"
              }
          }
      }
