AWSTemplateFormatVersion: '2010-09-09'
Description: Setup stack for application, including S3 bucket for templates, data and logs
Parameters:
  Stage:
    Type: String
    Description: Stage of production
  AppName:
    Type: String
  EC2KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key pair name for the Neo4j database server
  DataBucketName:
    Type: String
    Description: Name of bucket for application data and logs
  Neo4jUsername:
    Type: String
    NoEcho: true
  Neo4jPassword:
    Type: String
    NoEcho: true
Resources:
  Neo4jCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${Stage}-${AppName}-Neo4jCredentials"
      Description: Must match the username/password specified in the Neo4j Dockerfile
      SecretString: !Sub '{"username":"${Neo4jUsername}","password":"${Neo4jPassword}"}'
      Tags:
        - Key: Stage
          Value: !Ref Stage
        - Key: AppName 
          Value: !Ref AppName
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DataBucketName
  DataBucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub '/${AppName}/${Stage}/${AWS::Region}/DataBucketName'
      Description: "Name of gfe-db data bucket"
      Value: !Ref DataBucket
  DataBucketArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub '/${AppName}/${Stage}/${AWS::Region}/DataBucketArn'
      Description: "ARN of gfe-db data bucket"
      Value: !GetAtt DataBucket.Arn
Outputs:
  Stage:
    Description: Stage of production
    Value: !Ref Stage
    Export:
      Name: !Sub "${AWS::StackName}-Stage"
  AppName:
    Description: Name of application
    Value: !Ref AppName
    Export:
      Name: !Sub "${AWS::StackName}-AppName"
  EC2KeyPairName:
    Description: "EC2 key pair for launching instances"
    Value: !Ref EC2KeyPairName
    Export:
      Name: !Sub "${AWS::StackName}-EC2KeyPairName"
  DataBucketName:
    Description: "S3 Bucket for application bucket"
    Value: !Ref DataBucketName
    Export:
      Name: !Sub "${AWS::StackName}-DataBucketName"
  DataBucketArn:
    Description: "S3 Bucket Arn for application bucket"
    Value: !GetAtt DataBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DataBucketArn"
  DataBucketRegionalDomainName:
    Description: "S3 Bucket Regional Domain name for application bucket"
    Value: !GetAtt DataBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DataBucketRegionalDomainName"
