AWSTemplateFormatVersion: 2010-09-09
Description: Systems Manager Document for remote backup

Parameters:

  Stage:
    Type: String
    Description: Stage of production
  AppName:
    Type: String
    Description: Application name

Resources:

  Neo4jBackupDocument: 
    Type: AWS::SSM::Document
    Properties:
      DocumentType: "Command"
      DocumentFormat: "YAML"
      TargetType: "/AWS::EC2::Instance"
      Content:
        schemaVersion: "2.2"
        description: "Neo4j to S3 backup"
        parameters:
          sourceType:
            type: "String"
            description: "(Required) Specify the source type."
            default: "S3"
          sourceInfo:
            type: "StringMap"
            description: "(Required) Specify the information required to access the resource from the source. If source type is GitHub, then you can specify any of the following: 'owner', 'repository', 'path', 'getOptions', 'tokenInfo'. If source type is S3, then you can specify 'path'."
            default:
              path: "https://dev-gfe-db-531868584498-us-east-1.s3.amazonaws.com/config/scripts/backup.sh"
          commandLine:
            type: "String"
            description: "(Required) Specify the command line to be executed. The following formats of commands can be run: 'pythonMainFile.py argument1 argument2', 'ansible-playbook -i \"localhost,\" -c local example.yml'"
            default: "backup.sh"
          workingDirectory:
            type: "String"
            description: "Working directory"
            default: "/home/ubuntu"
          executionTimeout:
            type: "String"
            description: "(Optional) The time in seconds for a command to complete before it is considered to have failed. Default is 3600 (1 hour). Maximum is 28800 (8 hours)."
            default: "600"
        mainSteps:
          - action: "aws:downloadContent"
            name: "downloadContent"
            inputs:
              sourceType: "{{ sourceType }}"
              sourceInfo: "{{ sourceInfo }}"
              destinationPath: "{{ workingDirectory }}"
          - action: "aws:runShellScript"
            name: "runShellScript"
            inputs: 
              runCommand:
                - ""
                - "directory=$(pwd)"
                - "export PATH=$PATH:$directory"
                - " {{ commandLine }} " 
                - ""
              workingDirectory: "{{ workingDirectory }}"
              timeoutSeconds: "{{ executionTimeout }}"

  Neo4jBackupMaintenanceWindow:
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      AllowUnassociatedTargets: false
      Cutoff: 1
      Description: !Sub "${AppName} Neo4j backup maintenance window"
      Duration: 2
      Name: BackupNeo4jMaintenanceWindow
      Schedule: cron(0 * ? * * *)
      ScheduleTimezone: US/Eastern

  Neo4jBackupMaintenanceWindowTask:
    Type: AWS::SSM::MaintenanceWindowTask
    Properties:
      Description: Backup a Neo4j instance
      CutoffBehavior: CONTINUE_TASK
      MaxConcurrency: 1
      MaxErrors: 1
      Priority: 0
      TaskType: RUN_COMMAND
      WindowId: !Ref Neo4jBackupMaintenanceWindow
      TaskArn: !Ref Neo4jBackupDocument
      Targets:
        - Key: WindowTargetIds
          Values:
            - !Ref Neo4jBackupMaintenanceWindowTarget

  Neo4jBackupMaintenanceWindowTarget:
    Type: AWS::SSM::MaintenanceWindowTarget
    Properties:
      ResourceType: INSTANCE
      Targets:
        - Key: InstanceIds
          Values:
            - !Sub '{{resolve:ssm:/${AppName}/${Stage}/${AWS::Region}/Neo4jDatabaseInstanceId}}'
      WindowId: !Ref Neo4jBackupMaintenanceWindow