AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys a NAT Gateway with an Elastic IP address.

Parameters:
  Stage:
    Type: String
    Description: Stage of production
  AppName:
    Type: String
    Description: Application name
  
Resources: 
  # Required for NAT Gateway
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Sub '{{resolve:ssm:/${AppName}/${Stage}/${AWS::Region}/VpcId}}'

  # Required for NAT Gateway
  PrivateRouteTableParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub '/${AppName}/${Stage}/${AWS::Region}/PrivateRouteTableId'
      Description: !Sub "ID of the private route table for ${AppName}"
      Value: !Ref PrivateRouteTable

  # Required for NAT Gateway  
  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Sub '{{resolve:ssm:/${AppName}/${Stage}/${AWS::Region}/PrivateSubnetId}}'

  NatGatewayElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${Stage}-${AppName}-nat-gateway'

  NatGatewayElasticIpParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub '/${AppName}/${Stage}/${AWS::Region}/NatGatewayElasticIp'
      Description: "Elastic IP address of the NAT Gateway"
      Value: !Ref NatGatewayElasticIp

  NatGatewayElasticIpAllocationIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub '/${AppName}/${Stage}/${AWS::Region}/NatGatewayElasticIpAllocationId'
      Description: "Elastic IP address of the NAT Gateway"
      Value: !GetAtt NatGatewayElasticIp.AllocationId

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayElasticIp.AllocationId
      SubnetId: !Sub '{{resolve:ssm:/${AppName}/${Stage}/${AWS::Region}/PublicSubnetId}}'
      Tags:
        - Key: Name
          Value: !Sub '${Stage}-${AppName}-nat-gateway'

  NatGatewayIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub '/${AppName}/${Stage}/${AWS::Region}/NatGatewayId'
      Description: "NAT Gateway ID"
      Value: !Ref NatGateway

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      # RouteTableId: !Sub '{{resolve:ssm:/${AppName}/${Stage}/${AWS::Region}/PrivateRouteTableId}}'
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
